name: Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --configuration Release --no-restore

    - name: Pack the project
      run: dotnet pack --configuration Release --no-restore --no-build -o ./artifacts

    - name: Set version dynamically
      id: get_version
      run: |
        VERSION=$(date +"%Y.%m.%d.%H%M")
        echo "##[set-output name=version;]$VERSION"
      shell: bash

    - name: Publish to NuGet
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: |
        dotnet nuget push ./artifacts/*.nupkg \
          --source https://api.nuget.org/v3/index.json \
          --api-key $NUGET_API_KEY
        sed -i "s/<Version>.*<\/Version>/<Version>${{ steps.get_version.outputs.version }}<\/Version>/" ./Ros2DotnetUI.Library.csproj
        dotnet pack --configuration Release --no-restore --no-build --output ./artifacts
