name: Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Restore dependencies
      run: dotnet restore src/Ros2DotnetUI.Library/Ros2DotnetUI.Library.csproj

    - name: Build the project
      run: dotnet build src/Ros2DotnetUI.Library/Ros2DotnetUI.Library.csproj --configuration Release --no-restore

    - name: Set version dynamically
      id: get_version
      run: |
        VERSION=$(date +"%Y.%m.%d.%H%M")
        echo "VERSION=$VERSION" >> $GITHUB_ENV
      shell: bash

    - name: Pack the project
      run: |
        dotnet pack src/Ros2DotnetUI.Library/Ros2DotnetUI.Library.csproj \
          --configuration Release \
          --output ./artifacts \
          -p:PackageVersion=${{ env.VERSION }} \

    - name: Publish to NuGet
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: |
        dotnet nuget push ./artifacts/*.nupkg \
          --source https://api.nuget.org/v3/index.json \
          --api-key $NUGET_API_KEY
